name: Deploy Website to EC2

on:
  push:
    branches:
      - main   # trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: |
          index.html
          about.html
          book.html
          menu.html
          css/
          js/
          images/
          fonts/
        target: /home/${{ secrets.EC2_USER }}/mywebsite
        rm: true
        strip_components: 0
        timeout: 30s
        command_timeout: 10m
        overwrite: true
        tar_exec: tar
